### ISSUE TITLE
Timeout kills Homeassistant

### ISSUE THREAD

**Issue by eifinger** [custom-components/breaking_changes#13]
## Version of the custom_component

0.3.2
## Describe the bug
hachanges.halfdecent.io is down.
This seems to impact this component which kills my whole homeassistant. Startup when this component is added is about 20 minutes and after that homeassistant only reacts every 2 minutes to any input from the outside.
Somehow the failed update interacts with the async loop in ways it shouldn't.

## `custom_updater` configuration

```yaml

# Add configuration here

```

## Debug log

```text

Could not update data - HTTPSConnectionPool(host='hachanges.halfdecent.io', port=443): Max retries exceeded with url: /97/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9fb3440d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```

**Comment by rschuiling** [comment]
More people are experiencing this; please check https://community.home-assistant.io/t/unable-to-reach-home-assistant-ui-ssh/131204?u=emphyrio

**Comment by ludeeus** [comment]
Server is down (locked in a stopping state), not sure when it will be fixed.

**Comment by eifinger** [comment]
An idea how it can be that a timeout can affect home-assistant I'm such a way? I am thinking if this should be investigated and safeguards put into place inside home-assistant itself so a (custom)component can't bring down the whole system.

**Comment by ludeeus** [comment]
Not really, I have never seen that behavior before.

**Comment by ludeeus** [comment]
How fun....
I'm not able to replicate this in my env, everything start-up and are responsive 🤷‍♂

**Comment by ludeeus** [comment]
Pushed a release that _maybe_ will fix it, but since I did not have the issue I can not confirm that.
https://github.com/custom-components/breaking_changes/releases/tag/0.3.3

**Comment by Mike-Allen** [comment]
> Pushed a release that _maybe_ will fix it, but since I did not have the issue I can not confirm that.
> https://github.com/custom-components/breaking_changes/releases/tag/0.3.3

I manually applied the changes (and restarting HA) allowed me to access the Home Assistant UI.

I'm running HA in a Debian python virtual env ver 0.93.2. This morning I was no longer able to access the HA UI and things were running very slowly.

Thanks for your fix.
