### ISSUE TITLE
Unable to run after latest HA Docker update

### ISSUE THREAD

**Issue by Kallb123** [custom-components/breaking_changes#14]
## Version of the custom_component

Latest 0.3.3 custom_components/breaking_changes
Latest HA 0.97.2
Latest Docker homeassistant/home-assistant image

## Describe the bug

When starting HA, the custom component fails to start due to a missing package. I tried installing the package on the docker host, but that obviously doesn't help. Is this component not compatible with the default docker image?

## `custom_updater` configuration

No config, just copied the latest version into config folder as before

## Debug log

```text

Unable to install package integrationhelper==0.2.1: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/integrationhelper'
Consider using the `--user` option or check the permissions.
Not initializing breaking_changes because could not install requirement integrationhelper==0.2.1

```

**Comment by ludeeus** [comment]
It is, you have permission issues with how you run the container.

```
EnvironmentError: [Errno 13] Permission denied
```
