### ISSUE TITLE
Loaded components are ignored

### ISSUE THREAD

**Issue by springstan** [custom-components/breaking_changes#23]
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
version | 0.103.6
virtualenv | false

## Version of the custom_component
3.6

## Describe the bug

- all breaking changes are loaded instead of only loading the breaking changes that are based on the loaded components

## `custom_updater` configuration

```yaml

breaking_changes:

```

## Debug log

```text
DEBUG (MainThread) [custom_components.breaking_changes] Loaded components [all my components...]
```

**Comment by springstan** [comment]
This is still an issue.

**Comment by gadgetchnnel** [comment]
It looks like this may be an issue with how https://hachanges.halfdecent.io/ is scraping the release notes. Every breaking change has **component** as null and **doclink** as "https://www.home-assistant.io/components/None" which is causing it to treat them as being related to the **homeassistant** component which would always be loaded.

**Comment by springstan** [comment]
@gadgetchnnel good catch! Did not inspect https://hachanges.halfdecent.io/ at all but your explanation makes a lot of sense to me.

**Comment by colinfrei** [comment]
afaict this is because components were renamed to integrations. I've submitted a merge request here which I hope will fix that in the code checking for breaking changes: https://github.com/ludeeus/furystoolbox/pull/1

**Comment by ludeeus** [comment]
The new website is live with correct integration names https://hachanges.halfdecent.io/105
