### ISSUE TITLE
Does this component do any real logic?

### ISSUE THREAD

**Issue by 26tajeen** [custom-components/breaking_changes#24]
When I look at the breaking changes sensor, it shows all manner of potential breaking changes that have nothing to do with my setup or integrations.

**Comment by ludeeus** [comment]
It does
But the API it checks is "broken" due to layout changes in the release notes, so instead of showing 0, it falls back to showing all

**Comment by 26tajeen** [comment]
thanks, good to know

**Comment by ludeeus** [comment]
The new website is live with correct integration names https://hachanges.halfdecent.io/105
