### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by damousys** [custom-components/breaking_changes#27]
If I go to https://hachanges.halfdecent.io/ the site isn't available 
Also acourding to this site 

https://downforeveryoneorjustme.com/hachanges.halfdecent.io

**Comment by monotonus** [comment]
Yes I also get a Error 502 Bad Gateway.

**Comment by ludeeus** [comment]
There were structural changes in the new version (0.110) that the code did not handle.
This resulted in too much usage of the server which eventually died.
The code has been adjusted and server has been restored.
